### ISSUE TITLE
Creates posts and media folder but populates neither.

### ISSUE THREAD

**Issue by Leopere** [samirelanduk/reddit-save#8]
Been working on using the Docker container with a restart policy of once every few minutes so I can capture things regularly however the problem is I can't validate that this works at all yet.  There are no container logs.

```Dockerfile
FROM jrottenberg/ffmpeg:4.0-alpine

ENV PYTHONUNBUFFERED=1
ENV DOCKER=1 

RUN apk add build-base && apk add python3-dev

RUN echo "**** install Python ****" && \
    apk add --no-cache python3 bash && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    \
    echo "**** install pip ****" && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --no-cache --upgrade pip setuptools wheel && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi


COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip install -r requirements.txt
COPY . .

# ENTRYPOINT  ["python", "save.py"]
ENTRYPOINT /bin/bash
CMD           ["python", "save.py", "upvoted"]
```

```yaml
version: "3.9"    
services:
  reddit-save:
    build: .
    image: registry.REDACTED/reddit-save:latest
    command: ["python", "save.py", "saved"]
    environment:
      REDDIT_USERNAME: "REDACTED"
      REDDIT_PASSWORD: "REDACTED"
      REDDIT_CLIENT_ID: "REDACTED"
      REDDIT_SECRET: "REDACTED"
    volumes:
      - "./archive:/opt/app/archive"
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
```
